spring:
  profiles:
    active:
      - local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adwp_work1
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000 # 10 minutes
      connection-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'validate' for production
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: pwd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
